
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";



export const metadata = {
  title: "Tackles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar/>
        <main className="bg-white" >
        {children}
          </main>
        <Footer image={'/footer1.jpg'}/>

      </body>
    </html>
  );
}
